#!/bin/bash
foreground=$1
background=$2
font=$3

# Check to see if external is connected, if it is, we assume its 4K 
if [[ -n `xrandr | grep " connected" | grep "^DP1"` ]]; then
		conky -qc /home/tom/.xmonad/.conky_dzen | dzen2 -x '1800' -w '2000' -h '60'  -ta 'r' -bg $background -fg $foreground -y '40' -fn $font -dock &
		#	conky -qc /home/tom/.xmonad/.conky_dzen1 | dzen2 -x '0' -w '1120' -ta 'l' -bg $background -fg $foreground -y '0' -fn $font -dock &
else 
		#nitrogen --restore
		conky -qc /home/tom/.xmonad/.conky_dzen | dzen2 -x '1800' -tw '1360' -w '1360'  -h '60' -ta 'r' -bg $background -fg $foreground -y '40' -fn $font -dock &
#		conky -qc /home/tom/.xmonad/.conky_dzen | dzen2 -x '1800' -w '1360'  -h '40' -ta 'r' -bg $background -fg $foreground -y '20' -fn $font -dock &
		conky -qc /home/tom/.xmonad/.conky_dzen1 | dzen2 -x '0' -tw '1340' -w '1340' -h '60'  -ta 'r' -bg $background -fg $foreground -y '40' -fn $font -dock &
		#conky -qc /home/sunn/.xmonad/.conky_dzen2 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
		#conky -qc /home/sunn/.xmonad/.conky_dzen3 | dzen2 -x '1200' -w '720' -h '14' -ta 'r' -bg $background -fg $foreground -y '0' -fn $font -dock &
fi
